### PR TITLE
Fix #322, patched ACS, suppressed warnings regarding ACS::TimeInterval

### LINKED ISSUE #322: Apply a patch to ACS in order to avoid displaying warnings about some ACS::TimeInterval/long long unsigned int variable

### PR DESCRIPTION
**Pull request by giuseppe-carboni**
In the `enumpropAlarm.h` file under
`/alma/ACS-FEB2017/ACSSW/Sources/enumprop/ws/include/`, the `interval_m`
variable was declared as `ACS::TimeInterval`. In the `enumpropAlarm.i`
file, under the same directory, a sscanf operation is performed and a
`long long unsigned int` gets stored inside the `interval_m` variable
(internally, the `ACS::TimeInterval` class is indeed a `long long
unsigned int`). The sscanf operation, at compile time, continuously yields
a warning message about this, cluttering the building process output,
making it hard to notice other warning or error messages. This fix
simply changes the type of the `interval_m` variable to `long long
unsigned int`.

### CODE REVIEW

**Comment by giuseppe-carboni** [comment]
I used the same approach we used for the ACS Command Center long ago, replacing the whole file. I chose not to use the `lineinfile` module since there are multiple, non-contiguous lines to be replaced/added. If we happen to switch to a newer ACS version we should check the new files are not (too) different anyway, the `lineinfile` module could still fail even in this scenario. Up to you.

**Comment by aorlati** [comment]
Ok. Can you add a task to compare (diff) the original file (the one to be replaced) with one we have in the inventory?

**Comment by marco-buttu** [comment]
@aorlati we can also check the ACS version: if it is still the current one, ansible applies the patch, otherwise it fails and we remember to edit the new ACS file using it instead of the old one

**Comment by aorlati** [comment]
It could be a nice solution.

**Pull request merged**
